name: Release dotnet-ws tool

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.301

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_PACKAGE }}
          fetch-depth: 0

      - name: Build and package
        run: ./build.cmd
        env:
          VERSION_PATCH: ${{ github.run_number }}

      - name: Push package
        run:
          dotnet nuget push *.nupkg
          --api-key ${{ secrets.NUGET_API_KEY }}
          --source https://api.nuget.org/v3/index.json
          --skip-duplicate
          --timeout 1800
        working-directory: publish